### PR TITLE
Migrate from Javax Mail to Jakarta Mail

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by valfirst** [comment]
@svasenkov could you please review the changes? Also it would be good to review PRs from dependabot bumping various dependencies

**Comment by valfirst** [comment]
@svasenkov is there any chance to bring your attention to the opened PRs?

**Comment by svasenkov** [comment]
> @svasenkov is there any chance to bring your attention to the opened PRs?

Yes, ill have a look

**Comment by valfirst** [comment]
@svasenkov would you be able to review the opened PRs with all due respect to your workload? some transitive dependencies have CVE-s and it may bring a lot of pain to secured projects

**Comment by valfirst** [comment]
@svasenkov, pinging with soft reminder to review PRs

**Comment by valfirst** [comment]
@svasenkov one more reminder...

**Pull request merged**
